<?php

namespace AppBundle\Repository;

/**
 * MapTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
