<?php

namespace AppBundle\Repository;

/**
 * OW_MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OW_MatchRepository extends \Doctrine\ORM\EntityRepository
{
}
