<?php

namespace AppBundle\Repository;

/**
 * PlayedMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayedMapRepository extends \Doctrine\ORM\EntityRepository
{
}
